<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>50f705a7-87ab-4c13-8537-3e2aaa2856c8</testSuiteGuid>
   <testCaseLink>
      <guid>8c65cd48-dfb3-486c-9c46-682f874060d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>635817db-eae2-40ed-ad58-e49c79f40ddd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data (1)</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>635817db-eae2-40ed-ad58-e49c79f40ddd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>1f5bb6e9-0811-4dbc-8e3c-dd71af561e87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>635817db-eae2-40ed-ad58-e49c79f40ddd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5998c75e-ea54-42bf-9683-044dd23ca6c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c012a4cf-b049-42d6-b277-d5bcf889a3d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/test/Search</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
